export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SET_CLIENT = 'SET_CLIENT'
